// Single source of truth for every URL in the app.
// Components import PATHS instead of hardcoding path strings.

export const PATHS = {
  home: "/",
  shop: "/shop",
  product: "/product/:productId",
  productLink: (id) => `/product/${id}`,
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  about: "/about",
  contact: "/contact",
  shippingPolicy: "/shipping-policy",
  returnPolicy: "/return-policy",
  faq: "/faq",
  trackOrder: "/track-order",
  privacyPolicy: "/privacy-policy",
  terms: "/terms",
  login: "/login",
  register: "/register",
  profile: "/account",
  admin: {
    root: "/admin",
    login: "/admin/login",
    mfaSetup: "/admin/mfa-setup",
    dashboard: "/admin/dashboard",
    products: "/admin/products",
    newProduct: "/admin/products/new",
    editProductPath: "/admin/products/:id/edit",
    editProduct: (id) => `/admin/products/${id}/edit`,
    orders: "/admin/orders",
    orderDetailPath: "/admin/orders/:id",
    orderDetail: (id) => `/admin/orders/${id}`,
    customers: "/admin/customers",
    customerDetailPath: "/admin/customers/:id",
    customerDetail: (id) => `/admin/customers/${id}`,
    reviews: "/admin/reviews",
    subscribers: "/admin/subscribers",
    settings: "/admin/settings",
    heroSlides: "/admin/settings/hero-slides",
    newHeroSlide: "/admin/settings/hero-slides/new",
    editHeroSlidePath: "/admin/settings/hero-slides/:id/edit",
    editHeroSlide: (id) => `/admin/settings/hero-slides/${id}/edit`,
    coupons: "/admin/coupons",
    newCoupon: "/admin/coupons/new",
    editCouponPath: "/admin/coupons/:id/edit",
    editCoupon: (id) => `/admin/coupons/${id}/edit`,
  },
};
